const pokemonNameElem = document.getElementById("pokemon-name")
const pokemonIdElem = document.getElementById("pokemon-id")
const pokemonSpeciesElem = document.getElementById("pokemon-species")
const pokemonTypeElem = document.getElementById("pokemon-type")
const pokemonHeightElem = document.getElementById("pokemon-height")
const pokemonWeightElem = document.getElementById("pokemon-weight")
const pokemonFamilyTreeElem = document.getElementById("pokemon-family-tree")
const pokemonDescriptionElem = document.getElementById("pokemon-description")
